# Generated by Django 4.2.4 on 2023-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meeting_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(to='events1.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
